name: TaxiContainers
favicon: null
layout_spectrum: 0.018177860882133245
typography_spectrum: 0.2810449057724327
title: 'TaxiContainers - Mini Bodegas móviles a Domicilio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#ADD7F6'
    - '#87BFFF'
    - '#3F8EFC'
    - '#2667FF'
    - '#3B28CC'
  brandStrength: 0.38279416412115097
  lightness: 0.6535208278801292
  saturation: 0.8535032703075558
  rhythmicContrast: 0.19439889420755208
purpose: []
