name: TaxiContainers
favicon: null
layout_spectrum: 0
typography_spectrum: 1
title: 'TaxiContainers - Mini Bodegas móviles a Domicilio '
cta:
  domain: null
  bucket: null
  version: null
analytics:
  google: null
  facebook: null
  twitter: null
opengraph:
  image: null
  type: null
  appId: null
color:
  brandColors:
    - '#f8d124'
    - '#000000'
    - '#efdf9f'
    - '#fff7cf'
    - '#ffffff'
  brandStrength: 0.25
  lightness: 0.6535208278801292
  saturation: 0.8125
  rhythmicContrast: 0.25
purpose: []
